all: c_structure ex_class ex_make_outside_fun_inline ex_nesting_of_member_functions ex_processing_shipping_list ex_static_data_member ex_static_member_function ex_arrays_of_objects ex_objects_as_args ex_friend_function ex_func_friendly_to_two_classes ex_friend_class ex_swap_class_private_data ex_returning_objects ex_pointer_to_member ex_pointer_to_member_function

c_structure: c_structure.cpp
	g++ c_structure.cpp -o c_structure

ex_class: ex_class.cpp
	g++ ex_class.cpp -o ex_class

ex_make_outside_fun_inline: ex_make_outside_fun_inline.cpp
	g++ ex_make_outside_fun_inline.cpp -o ex_make_outside_fun_inline

ex_nesting_of_member_functions: ex_nesting_of_member_functions.cpp
	g++ ex_nesting_of_member_functions.cpp -o ex_nesting_of_member_functions

ex_processing_shipping_list: ex_processing_shipping_list.cpp
	g++ ex_processing_shipping_list.cpp -o ex_processing_shipping_list

ex_static_data_member: ex_static_data_member.cpp
	g++ ex_static_data_member.cpp -o ex_static_data_member

ex_static_member_function: ex_static_member_function.cpp
	g++ ex_static_member_function.cpp -o ex_static_member_function

ex_arrays_of_objects: ex_arrays_of_objects.cpp
	g++ ex_arrays_of_objects.cpp -o ex_arrays_of_objects

ex_objects_as_args: ex_objects_as_args.cpp
	g++ ex_objects_as_args.cpp -o ex_objects_as_args

ex_friend_function: ex_friend_function.cpp
	g++ ex_friend_function.cpp -o ex_friend_function

ex_func_friendly_to_two_classes: ex_func_friendly_to_two_classes.cpp
	g++ ex_func_friendly_to_two_classes.cpp -o ex_func_friendly_to_two_classes

ex_friend_class: ex_friend_class.cpp
	g++ ex_friend_class.cpp -o ex_friend_class

ex_swap_class_private_data: ex_swap_class_private_data.cpp
	g++ ex_swap_class_private_data.cpp -o ex_swap_class_private_data

ex_returning_objects: ex_returning_objects.cpp
	g++ ex_returning_objects.cpp -o ex_returning_objects

ex_pointer_to_member: ex_pointer_to_member.cpp
	g++ ex_pointer_to_member.cpp -o ex_pointer_to_member

ex_pointer_to_member_function: ex_pointer_to_member_function.cpp
	g++ ex_pointer_to_member_function.cpp -o ex_pointer_to_member_function

clean:
	del *.exe
