all: c_structure ex_class ex_make_outside_fun_inline ex_nesting_of_member_functions ex_processing_shipping_list

c_structure: c_structure.cpp
	g++ c_structure.cpp -o c_structure

ex_class: ex_class.cpp
	g++ ex_class.cpp -o ex_class

ex_make_outside_fun_inline: ex_make_outside_fun_inline.cpp
	g++ ex_make_outside_fun_inline.cpp -o ex_make_outside_fun_inline

ex_nesting_of_member_functions: ex_nesting_of_member_functions.cpp
	g++ ex_nesting_of_member_functions.cpp -o ex_nesting_of_member_functions

ex_processing_shipping_list: ex_processing_shipping_list.cpp
	g++ ex_processing_shipping_list.cpp -o ex_processing_shipping_list

clean:
	del *.exe
