all: c_structure ex_class ex_make_outside_fun_inline ex_nesting_of_member_functions

c_structure: c_structure.cpp
	g++ c_structure.cpp -o c_structure

ex_class: ex_class.cpp
	g++ ex_class.cpp -o ex_class

ex_make_outside_fun_inline: ex_make_outside_fun_inline.cpp
	g++ ex_make_outside_fun_inline.cpp -o ex_make_outside_fun_inline

ex_nesting_of_member_functions: ex_nesting_of_member_functions.cpp
	g++ ex_nesting_of_member_functions.cpp -o ex_nesting_of_member_functions

clean:
	del *.exe
