CC = g++
CCFLAGS = -std=c++11

all: ex_creating_string_objects ex_modifying_string_objects ex_relational_operations_on_string_objects ex_string_characteristic ex_accessing_and_manipulating_characters ex_comparing_and_swapping_strings

ex_creating_string_objects: ex_creating_string_objects.cpp 
	$(CC) $(CCFLAGS) ex_creating_string_objects.cpp -o ex_creating_string_objects

ex_modifying_string_objects: ex_modifying_string_objects.cpp 
	$(CC) $(CCFLAGS) ex_modifying_string_objects.cpp -o ex_modifying_string_objects

ex_relational_operations_on_string_objects: ex_relational_operations_on_string_objects.cpp 
	$(CC) $(CCFLAGS) ex_relational_operations_on_string_objects.cpp -o ex_relational_operations_on_string_objects

ex_string_characteristic: ex_string_characteristic.cpp 
	$(CC) $(CCFLAGS) ex_string_characteristic.cpp -o ex_string_characteristic

ex_accessing_and_manipulating_characters: ex_accessing_and_manipulating_characters.cpp 
	$(CC) $(CCFLAGS) ex_accessing_and_manipulating_characters.cpp -o ex_accessing_and_manipulating_characters

ex_comparing_and_swapping_strings: ex_comparing_and_swapping_strings.cpp 
	$(CC) $(CCFLAGS) ex_comparing_and_swapping_strings.cpp -o ex_comparing_and_swapping_strings

clean:
	del *.exe
