CC = g++
CCFLAGS = -std=c++11

all: ex_try_block_throwing_exception 

ex_try_block_throwing_exception: ex_try_block_throwing_exception.cpp 
	$(CC) $(CCFLAGS) ex_try_block_throwing_exception.cpp -o ex_try_block_throwing_exception

clean:
	del *.exe
