all: ex_void ex_enum ex_array ex_pointers ex_sym_const ex_var ex_scope_resol ex_mem_management ex_type_cast ex_expressions

ex_void: ex_void.cpp
	g++ ex_void.cpp -o ex_void

ex_enum: ex_enum.cpp
	g++ ex_enum.cpp -o ex_enum

ex_array: ex_array.cpp
	g++ ex_array.cpp -o ex_array

ex_pointers: ex_pointers.cpp
	g++ ex_pointers.cpp -o ex_pointers

ex_sym_const: ex_sym_const.cpp
	g++ ex_sym_const.cpp -o ex_sym_const

ex_var: ex_var.cpp
	g++ ex_var.cpp -o ex_var

ex_scope_resol: ex_scope_resol.cpp
	g++ ex_scope_resol.cpp -o ex_scope_resol

ex_mem_management: ex_mem_management.cpp
	g++ ex_mem_management.cpp -o ex_mem_management

ex_type_cast: ex_type_cast.cpp
	g++ ex_type_cast.cpp -o ex_type_cast

ex_expressions: ex_expressions.cpp
	g++ ex_expressions.cpp -o ex_expressions

clean:
	del *.exe
