all: ex_void ex_enum ex_array

ex_void: ex_void.cpp
	g++ ex_void.cpp -o ex_void

ex_enum: ex_enum.cpp
	g++ ex_enum.cpp -o ex_enum

ex_array: ex_array.cpp
	g++ ex_array.cpp -o ex_array

clean:
	del *.exe
