CC = g++
CCFLAGS = -std=c++11

all: ex_using_vector ex_using_list ex_using_map

ex_using_vector: ex_using_vector.cpp 
	$(CC) $(CCFLAGS) ex_using_vector.cpp -o ex_using_vector

ex_using_list: ex_using_list.cpp 
	$(CC) $(CCFLAGS) ex_using_list.cpp -o ex_using_list

ex_using_map: ex_using_map.cpp 
	$(CC) $(CCFLAGS) ex_using_map.cpp -o ex_using_map

clean:
	del *.exe
