CC = g++
CCFLAGS = -s

all: ex_pointers ex_manipulation_of_pointers ex_arithmetic_operation_on_pointers ex_pointers_with_array

ex_pointers: ex_pointers.cpp
	$(CC) $(CCFLAGS) ex_pointers.cpp -o ex_pointers

ex_manipulation_of_pointers: ex_manipulation_of_pointers.cpp
	$(CC) $(CCFLAGS) ex_manipulation_of_pointers.cpp -o ex_manipulation_of_pointers

ex_arithmetic_operation_on_pointers: ex_arithmetic_operation_on_pointers.cpp
	$(CC) $(CCFLAGS) ex_arithmetic_operation_on_pointers.cpp -o ex_arithmetic_operation_on_pointers

ex_pointers_with_array: ex_pointers_with_array.cpp
	$(CC) $(CCFLAGS) ex_pointers_with_array.cpp -o ex_pointers_with_array

clean:
	del *.exe
