CC = g++
CCFLAGS = -s

all: ex_pointers ex_manipulation_of_pointers ex_arithmetic_operation_on_pointers ex_pointers_with_array ex_arrays_of_pointers ex_pointer_and_strings ex_pointer_to_function ex_pointer_to_objects ex_array_of_pointers_to_objects ex_this_Pointer ex_pointer_to_derived_class ex_virtual_functions ex_runtime_polymorphism

ex_pointers: ex_pointers.cpp
	$(CC) $(CCFLAGS) ex_pointers.cpp -o ex_pointers

ex_manipulation_of_pointers: ex_manipulation_of_pointers.cpp
	$(CC) $(CCFLAGS) ex_manipulation_of_pointers.cpp -o ex_manipulation_of_pointers

ex_arithmetic_operation_on_pointers: ex_arithmetic_operation_on_pointers.cpp
	$(CC) $(CCFLAGS) ex_arithmetic_operation_on_pointers.cpp -o ex_arithmetic_operation_on_pointers

ex_pointers_with_array: ex_pointers_with_array.cpp
	$(CC) $(CCFLAGS) ex_pointers_with_array.cpp -o ex_pointers_with_array

ex_arrays_of_pointers: ex_arrays_of_pointers.cpp
	$(CC) $(CCFLAGS) ex_arrays_of_pointers.cpp -o ex_arrays_of_pointers

ex_pointer_and_strings: ex_pointer_and_strings.cpp
	$(CC) $(CCFLAGS) ex_pointer_and_strings.cpp -o ex_pointer_and_strings

ex_pointer_to_function: ex_pointer_to_function.cpp
	$(CC) $(CCFLAGS) ex_pointer_to_function.cpp -o ex_pointer_to_function

ex_pointer_to_objects: ex_pointer_to_objects.cpp
	$(CC) $(CCFLAGS) ex_pointer_to_objects.cpp -o ex_pointer_to_objects

ex_array_of_pointers_to_objects: ex_array_of_pointers_to_objects.cpp
	$(CC) $(CCFLAGS) ex_array_of_pointers_to_objects.cpp -o ex_array_of_pointers_to_objects

ex_this_Pointer: ex_this_Pointer.cpp
	$(CC) $(CCFLAGS) ex_this_Pointer.cpp -o ex_this_Pointer

ex_pointer_to_derived_class: ex_pointer_to_derived_class.cpp
	$(CC) $(CCFLAGS) ex_pointer_to_derived_class.cpp -o ex_pointer_to_derived_class

ex_virtual_functions: ex_virtual_functions.cpp
	$(CC) $(CCFLAGS) ex_virtual_functions.cpp -o ex_virtual_functions

ex_runtime_polymorphism: ex_runtime_polymorphism.cpp
	$(CC) $(CCFLAGS) ex_runtime_polymorphism.cpp -o ex_runtime_polymorphism

clean:
	del *.exe
