all: ex_call_by_reference ex_inline

ex_call_by_reference: ex_call_by_reference.cpp
	g++ ex_call_by_reference.cpp -o ex_call_by_reference

ex_inline: ex_inline.cpp
	g++ ex_inline.cpp -o ex_inline
clean:
	del *.exe
