CC = g++
CCFLAGS = -s

all: ex_character_io_with_get_and_put ex_reading_strings_with_getline ex_displaying_strings_with_write ex_specifying_field_size_with_width ex_precision_setting_with_precision ex_padding_with_fill

ex_character_io_with_get_and_put: ex_character_io_with_get_and_put.cpp
	$(CC) $(CCFLAGS) ex_character_io_with_get_and_put.cpp -o ex_character_io_with_get_and_put

ex_reading_strings_with_getline: ex_reading_strings_with_getline.cpp
	$(CC) $(CCFLAGS) ex_reading_strings_with_getline.cpp -o ex_reading_strings_with_getline

ex_displaying_strings_with_write: ex_displaying_strings_with_write.cpp
	$(CC) $(CCFLAGS) ex_displaying_strings_with_write.cpp -o ex_displaying_strings_with_write

ex_specifying_field_size_with_width: ex_specifying_field_size_with_width.cpp
	$(CC) $(CCFLAGS) ex_specifying_field_size_with_width.cpp -o ex_specifying_field_size_with_width

ex_precision_setting_with_precision: ex_precision_setting_with_precision.cpp
	$(CC) $(CCFLAGS) ex_precision_setting_with_precision.cpp -o ex_precision_setting_with_precision

ex_padding_with_fill: ex_padding_with_fill.cpp
	$(CC) $(CCFLAGS) ex_padding_with_fill.cpp -o ex_padding_with_fill

clean:
	del *.exe
