CC = g++
CCFLAGS = -s

all: ex_character_io_with_get_and_put

ex_character_io_with_get_and_put: ex_character_io_with_get_and_put.cpp
	$(CC) $(CCFLAGS) ex_character_io_with_get_and_put.cpp -o ex_character_io_with_get_and_put

clean:
	del *.exe
