CC = g++
CCFLAGS = -s

all: ex_character_io_with_get_and_put ex_reading_strings_with_getline

ex_character_io_with_get_and_put: ex_character_io_with_get_and_put.cpp
	$(CC) $(CCFLAGS) ex_character_io_with_get_and_put.cpp -o ex_character_io_with_get_and_put

ex_reading_strings_with_getline: ex_reading_strings_with_getline.cpp
	$(CC) $(CCFLAGS) ex_reading_strings_with_getline.cpp -o ex_reading_strings_with_getline

clean:
	del *.exe
