CC = g++
CCFLAGS = -std=c++11

all: ex_example_of_class_template

ex_example_of_class_template: ex_example_of_class_template.cpp
	$(CC) $(CCFLAGS) ex_example_of_class_template.cpp -o ex_example_of_class_template

clean:
	del *.exe
